### PR TITLE
Change to MIT license

### PR DESCRIPTION
**Pull request by thec00n**
@ersul4ik @s0b0lev @dmuhs @JoranHonig can you guys approve?

### CODE REVIEW

**Comment by s0b0lev** [comment]
Approve.

**Comment by ersul4ik** [comment]
Approve.

**Comment by dmuhs** [comment]
I figure this is the result of Joseph and the other people involved with management approving the license change, too? :slightly_smiling_face:

**Comment by thec00n** [comment]
@dmuhs the SWC related projects are all open source and the individual contributors decide on a license change.

**Comment by JoranHonig** [comment]
Approve

**Comment by dmuhs** [comment]
Approve

**Pull request merged**
